replicaCount: 1
image:
  repository: docker-registry:5000/myuser/python-app
  tag: latest
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
serviceAccountName: 
  create: true
ENVIRONMENT_NAME:
