apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: python

